version: '3.1'
services:

    # Application container
    dotnet:
        image: microsoft/dotnet
        build:
          context: .
          dockerfile: ./BookSellerWebAPI/Dockerfile
        environment:
          PORT: 5000
        volumes:
          - ./:/server/http
        links:
          - postgres
        ports:
          - "5000:80"

    postgres:
        image: onjin/alpine-postgres
        restart: unless-stopped
        ports:
            - "5453:5432"
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: book_seller
            POSTGRES_PASSWORD: book_seller
            POSTGRES_DB: book_seller
